Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Breadlesscode.ErrorPages': ['NodeTypes/*']
  Flow:
    error:
      exceptionHandler:
        renderingGroups:
          notFoundExceptions:
            matchingStatusCodes: [ 404, 410 ]
            options:
              templatePathAndFilename: 'resource://Breadlesscode.ErrorPages/Private/Templates/ErrorPage.html'
